apiVersion: batch/v1
kind: Job
metadata:
  name: ${USER}-job-ddp
  labels:
    eidf/user: ${USER}
    kueue.x-k8s.io/queue-name: ${INFK8S_QUEUE_NAME}
    kueue.x-k8s.io/priority-class: batch-workload-priority
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed
  backoffLimit: 2147483647
  activeDeadlineSeconds: 864000
  template:
    metadata:
      labels:
        eidf/user: ${USER}
      annotations:
        nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
      containers:
        - name: my-app
          image: kaiyaoed/my_app:latest
          workingDir: "/workspace/kubernets"
          env:
          - name: TORCH_NCCL_ASYNC_ERROR_HANDLING
            value: "1"
          - name: NCCL_SOCKET_IFNAME
            value: "lo"
          - name: NCCL_NSOCKS_PERTHREAD
            value: "4"
          - name: NCCL_SOCKET_NTHREADS
            value: "2"
          - name: NCCL_DEBUG
            value: "INFO"
          - name: NCCL_IB_DISABLE
            value: "1"
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Running experiment"
              mkdir -p /workspace/kubernets/results
              # First try to download the model file explicitly
              curl -o ffhq70k-paper256-ada.pkl "https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/paper-fig7c-training-set-sweeps/ffhq70k-paper256-ada.pkl"
              mkdir -p /workspace/kubernets/results
              torchrun --nproc_per_node=8 \
                      --nnodes=1 \
                      --node_rank=0 \
                      --master_addr=127.0.0.1 \
                      --master_port=12345 \
                      main.py train \
                      --stylegan2_url="https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/paper-fig7c-training-set-sweeps/ffhq70k-paper256-ada.pkl" \
                      --batch_size=8 \
                      --n_iterations=500000 \
                      --num_eval_samples=10000 \
                      --num_conv_layers=7 \
                      --num_pool_layers=7 \
                      --initial_channels=64 \
                      --lr_M_hat=2e-4 \
                      --lr_D=2e-4 \
                      --max_delta=0.2 \
                      --saving_path=results \
                      --mask_switch=True
              exit_status=$?
              echo "Python script finished with exit status $exit_status"
              sleep infinity
          resources:
            limits:
              nvidia.com/gpu: "8"
              cpu: "8"
              memory: "32Gi"
          volumeMounts:
            - name: workspace
              mountPath: /workspace/kubernets/results
            - name: nfs-user
              mountPath: /nfs-user
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: ${USER}-ws-ddp
        - name: nfs-user
          nfs:
            server: $INFK8S_NFS_SERVER_IP
            path: /user/$USER