apiVersion: batch/v1
kind: Job
metadata:
  name: ${USER}-job-ablation-${INDEX}
  labels:
    eidf/user: ${USER}
    kueue.x-k8s.io/queue-name: ${INFK8S_QUEUE_NAME}
    kueue.x-k8s.io/priority-class: batch-workload-priority
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed
  backoffLimit: 2147483647
  activeDeadlineSeconds: 86400
  template:
    metadata:
      labels:
        eidf/user: ${USER}
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        nvidia.com/gpu.present: "true"
      containers:
        - name: my-app
          image: kaiyaoed/my_app:latest
          workingDir: "/workspace/kubernets"
          env:
            - name: MAX_DELTA
              value: "${MAX_DELTA}"
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Running experiment with max_delta=$MAX_DELTA"
              mkdir -p /workspace/kubernets/results
              # Copy the checkpoint file from the NFS volume to the PVC
              cp /nfs-user/data/checkpoint_20250221204015484235.pt /workspace/kubernets/results/checkpoint_20250221204015484235.pt
              python3 -u main.py train \
                --stylegan2_url="https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/paper-fig7c-training-set-sweeps/ffhq70k-paper256-ada.pkl" \
                --batch_size=8 \
                --n_iterations=600 \
                --num_eval_samples=10000 \
                --num_conv_layers=7 \
                --num_pool_layers=7 \
                --initial_channels=64 \
                --lr_M_hat=2e-4 \
                --lr_D=2e-4 \
                --max_delta=$MAX_DELTA \
                --saving_path=results \
                --convergence_threshold=0.0000001 \
                --mask_switch=True \
                --resume_checkpoint=/workspace/kubernets/results/checkpoint_20250221204015484235.pt
              exit_status=$?
              echo "Python script finished with exit status $exit_status, sleeping indefinitely"
              sleep infinity
          resources:
            limits:
              nvidia.com/gpu: "1"  # Each job uses 1 GPU
              cpu: "4"
              memory: "16Gi"
          volumeMounts:
            - name: workspace
              mountPath: /workspace/kubernets/results
            - name: nfs-user
              mountPath: /nfs-user
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: ${USER}-ws-${INDEX}
        - name: nfs-user
          nfs:
            server: $INFK8S_NFS_SERVER_IP
            path: /user/$USER